# Generated by Django 6.0.3 on 2026-04-27 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Compétence')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la mission')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('heure', models.TimeField(verbose_name='Heure de début')),
                ('taux_horaire', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taux horaire (CFA)')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='missions/', verbose_name='Image')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermée'), ('pourvue', 'Pourvue')], default='ouverte', max_length=10, verbose_name='Statut')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('competences', models.ManyToManyField(blank=True, related_name='missions', to='recrutement.competence', verbose_name='Compétences requises')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='attente', max_length=10, verbose_name='Statut')),
                ('message', models.TextField(blank=True, verbose_name='Message de motivation')),
                ('postule_le', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='recrutement.mission', verbose_name='Mission')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-postule_le'],
                'unique_together': {('mission', 'candidat')},
            },
        ),
    ]
