# Generated by Django 6.0.3 on 2026-04-25 15:10

import django.db.models.deletion
import greenplay.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('media_type', models.CharField(choices=[('video', 'Vidéo'), ('image', 'Image'), ('audio', 'Audio')], max_length=10, verbose_name='Type de média')),
                ('file', models.FileField(upload_to=greenplay.models.media_upload_path, verbose_name='Fichier média')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=greenplay.models.thumbnail_upload_path, verbose_name='Miniature')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Auteur / Réalisateur')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Date de production')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (secondes)')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Taille du fichier (octets)')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('invite', 'Sur invitation')], default='public', max_length=10, verbose_name='Visibilité')),
                ('license', models.CharField(choices=[('proprietary', 'Propriétaire'), ('cc_by', 'CC BY'), ('cc_by_sa', 'CC BY-SA'), ('public_domain', 'Domaine public')], default='proprietary', max_length=20, verbose_name='Licence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to='greenplay.category', verbose_name='Catégorie')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to=settings.AUTH_USER_MODEL, verbose_name='Téléversé par')),
                ('tags', models.ManyToManyField(blank=True, related_name='medias', to='greenplay.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='greenplay.media')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vue',
                'verbose_name_plural': 'Vues',
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recherche',
                'verbose_name_plural': 'Recherches',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type'], name='greenplay_m_media_t_3c8182_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['visibility'], name='greenplay_m_visibil_0192cb_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['created_at'], name='greenplay_m_created_8131f9_idx'),
        ),
    ]
