# Generated by Django 6.0.3 on 2026-03-28 10:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('is_active', models.BooleanField(auto_created=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('image_url', models.ImageField(upload_to='uploads/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
